all:
	go build -o spot spot_main.go
	go build -o user_push user_push_main.go
	go build -o change change_main.go
	go build -o premium premium_main.go
	go build -o bigorder bigorder_main.go
	go build -o bigtrade bigtrade_main.go
	go build -o blastingorder blastingorder_main.go
	go build -o deliverydate deliverydate_main.go
	go build -o everydaymarket everydaymarket_main.go
	go build -o bbx_notify bbx_notify_main.go
	go build -o bbex_pushtest bbex_pushtest.go
clean:
	rm -rf spot user_push change premium bigorder bigtrade blastingorder deliverydate everydaymarket bbx_notify bbex_pushtest

